# Generated by Django 4.2.26 on 2025-11-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('done', 'Готово'), ('in_progress', 'В процессе'), ('cancelled', 'Отменено'), ('only_planned', 'Только запланировано'), ('waiting_to_start', 'Ожидает начала')], db_index=True, default='only_planned', max_length=32)),
                ('locked', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('furry_type', models.CharField(choices=[('yes', 'Фурри'), ('no', 'Не фурри')], default='no', max_length=32)),
                ('human_type', models.CharField(choices=[('yes', 'Человек'), ('no', 'Не человек')], default='yes', max_length=32)),
                ('is_nsfw', models.BooleanField(default=False)),
                ('is_sfw', models.BooleanField(default=False)),
                ('is_nsfw_plus_crop', models.BooleanField(default=False)),
                ('post_on_bsky', models.BooleanField(default=False)),
                ('post_on_lewd_twi', models.BooleanField(default=False)),
                ('post_on_decent_twi', models.BooleanField(default=False)),
                ('bsky_posted', models.CharField(choices=[('not_posted', 'Не выложено'), ('scheduled', 'Запланировано'), ('posted', 'Выложено')], default='not_posted', max_length=12)),
                ('lewd_twi_posted', models.CharField(choices=[('not_posted', 'Не выложено'), ('scheduled', 'Запланировано'), ('posted', 'Выложено')], default='not_posted', max_length=12)),
                ('decent_twi_posted', models.CharField(choices=[('not_posted', 'Не выложено'), ('scheduled', 'Запланировано'), ('posted', 'Выложено')], default='not_posted', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='art',
            constraint=models.CheckConstraint(check=models.Q(('is_nsfw_plus_crop', True), ('is_sfw', True), _negated=True), name='art_no_sfw_with_nsfw_plus_crop'),
        ),
        migrations.AddConstraint(
            model_name='art',
            constraint=models.CheckConstraint(check=models.Q(('is_nsfw_plus_crop', True), ('is_nsfw', False), _negated=True), name='art_nsfw_plus_crop_requires_nsfw'),
        ),
    ]
