# Generated by Django 4.2.26 on 2026-05-25 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_deleted_art_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('expected', 'Ожидается'), ('received', 'Получено у посредника'), ('withdrawn', 'Выведено')], db_index=True, default='expected', max_length=32)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_parts', to='core.art')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_month', models.CharField(db_index=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Месяц вывода должен быть в формате YYYY-MM.', regex='^\\d{4}-(0[1-9]|1[0-2])$')])),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_allocations', to='core.paymentpart')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.payout')),
            ],
        ),
    ]
