# Generated by Django 4.2.26 on 2026-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentpart_payout_payoutallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='is_fanart',
            field=models.BooleanField(db_index=True, default=False, help_text='Фанарт / личная работа без финансового блока.'),
        ),
        migrations.AlterField(
            model_name='art',
            name='payout_status',
            field=models.CharField(choices=[('not_withdrawn', 'Не выведено'), ('partially_withdrawn', 'Частично выведено'), ('withdrawn', 'Выведено')], db_index=True, default='not_withdrawn', max_length=32),
        ),
    ]
