# Generated by Django 4.2.26 on 2026-06-07 16:21

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_art_is_fanart_alter_art_payout_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_month', models.CharField(db_index=True, default=core.models.current_order_month, max_length=7, validators=[django.core.validators.RegexValidator(message='Месяц дохода должен быть в формате YYYY-MM.', regex='^\\d{4}-(0[1-9]|1[0-2])$')])),
                ('source', models.CharField(choices=[('patreon', 'Patreon'), ('boosty', 'Boosty'), ('tip', 'Типсы'), ('family', 'Родня'), ('state', 'Государство'), ('other', 'Другое')], db_index=True, default='other', max_length=32)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
