# Generated by Django 4.2.26 on 2026-06-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_externalincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIncomePayoutAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_income', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_allocations', to='core.externalincome')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_allocations', to='core.payout')),
            ],
        ),
    ]
