# Generated by Django 4.2.26 on 2026-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_externalincomepayoutallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='price_currency',
            field=models.CharField(choices=[('usd', 'USD'), ('rub', 'RUB')], default='usd', max_length=3),
        ),
        migrations.AddField(
            model_name='externalincome',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('rub', 'RUB')], default='usd', max_length=3),
        ),
        migrations.AddField(
            model_name='externalincome',
            name='received_via',
            field=models.CharField(choices=[('broker', 'Через посредника'), ('direct', 'Напрямую')], default='broker', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentpart',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('rub', 'RUB')], default='usd', max_length=3),
        ),
        migrations.AddField(
            model_name='paymentpart',
            name='received_via',
            field=models.CharField(choices=[('broker', 'Через посредника'), ('direct', 'Напрямую')], default='broker', max_length=16),
        ),
    ]
